### ISSUE TITLE
"Singular" is not an inflected form of "hasta" (or 80 other words)

### ISSUE THREAD

**Issue by aryamccarthy** [unimorph/lat#2]
This was called a "ridiculous paradigm" by someone who looked at our data.

lingua **Plural** N;NOM;PL
lingua linguā N;VOC;SG
lingua lingua N;GEN;SG
lingua linguae N;GEN;PL
lingua **Singular** N;NOM;SG
lingua linguae N;DAT;SG
lingua linguīs N;ACC;PL
lingua linguae N;ACC;SG
lingua linguīs N;VOC;PL
lingua linguās N;ABL;PL
lingua linguam N;ABL;SG
lingua linguārum N;DAT;PL

**Comment by kbatsuren** [comment]
With the current update, this and the macron issues are fixed.
